#pragma kernel InitialiseAttractorPoints
#pragma kernel IterateAttractorPoints

//RWStructuredBuffer<float4> _AttractorPoints;

RWByteAddressBuffer _AttractorPoints;

RWStructuredBuffer<float4x4> _AttractorMatrices;

int randomiseOffset;

uint iterationCount;

//RWStructuredBuffer<uint> _ArgsBuffer;


float hash(uint n) {
   // integer hash copied from Hugo Elias
   n = (n << 13U) ^ n;
   n = n * (n * n * 15731U + 0x789221U) + 0x1376312589U;
   return float(n & uint(0x7fffffffU)) / float(0x7fffffff);
}

[numthreads(256,1,1)]
void InitialiseAttractorPoints(uint3 id : SV_DispatchThreadID)
{
    uint gridWidth = 512;
    float x = (id.x % gridWidth) / (float)gridWidth;
    float y = (id.x / gridWidth) / (float)gridWidth;

    float3 pos = float3(x * 2 - 1, y * 2 - 1, 0);

 
 uint address = id.x * 12;
 _AttractorPoints.Store3(address, asuint(pos));

}


[numthreads(256,1,1)]
void IterateAttractorPoints(uint3 id : SV_DispatchThreadID)
{
   if (id.x >= iterationCount) {return;}
   
   
   float3 pos = asfloat(_AttractorPoints.Load3(id.x * 12));
   
   /*
   uint seed = hash(id.x + randomiseOffset * 1234);
   uint index = id.x % 3;
   float4x4 transform = _AttractorMatrices[index];
   float4 p = float4(pos.xyz,1.0f);
   pos = mul(transform,p);
   */
       
   
   
   
   
    uint address = id.x * 12;
    _AttractorPoints.Store3(address, asuint(pos));
}
