#pragma kernel InitialiseAttractorPoints
#pragma kernel IterateAttractor1Points
#pragma kernel IterateAttractor2Points
//#pragma kernel ScalePoints

#include "MathCore.cginc"


RWStructuredBuffer<float3> _AttractorPoints1;
RWStructuredBuffer<float3> _AttractorPoints2;
RWStructuredBuffer<MathCoreM4x4> _AttractorMatrices;


uint particleCount;
int affineTransformationCount;






float hash(uint n) {
   // integer hash copied from Hugo Elias
   n = (n << 13U) ^ n;
   n = n * (n * n * 15731U + 0x789221U) + 0x1376312589U;
   return float(n & uint(0x7fffffffU)) / float(0x7fffffff);
}



[numthreads(256,1,1)]
void InitialiseAttractorPoints(uint3 id : SV_DispatchThreadID)
{
    float3 pos = float3(id.x, 0, 0);
 
    _AttractorPoints1[id.x] = pos;
    _AttractorPoints2[id.x] = pos;
}


[numthreads(256,1,1)]
void IterateAttractor1Points(uint3 id : SV_DispatchThreadID)
{
   if (id.x >= particleCount) {return;}
    float3 pos = _AttractorPoints1[id.x];
    
    uint seed = id.x;
    for (int i = 0; i < 100; i++)
    {
        seed += i * 1926783;
        float r = hash(seed);
    
        uint index = (uint)(r * affineTransformationCount);
        pos = MathCoreMul(_AttractorMatrices[index],float4(pos,1)).xyz;
    }
    _AttractorPoints1[id.x] = pos;
}

[numthreads(256,1,1)]
void IterateAttractor2Points(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= particleCount) {return;}
    float3 pos = _AttractorPoints2[id.x];
    
    uint seed = id.x;
    for (int i = 0; i < 100; i++)
    {
        seed += i * 1926783;
        float r = hash(seed);
    
        uint index = (uint)(r * affineTransformationCount);
        pos = MathCoreMul(_AttractorMatrices[index],float4(pos,1)).xyz;
    }
    _AttractorPoints2[id.x] = pos;
}


