#pragma kernel InitialiseAttractorPoints
#pragma kernel IterateAttractorPoints
#pragma kernel ScalePoints

//RWStructuredBuffer<float4> _AttractorPoints;

RWByteAddressBuffer _AttractorPoints;

RWStructuredBuffer<float4x4> _AttractorMatrices;


uint iterationCount;



void WriteVertex(uint offset, float3 v) {
    uint addr = offset * 12;
    _AttractorPoints.Store3(addr, asuint(v));
}

float3 ReadVertex(uint offset) {
    uint addr = offset * 12;

    return asfloat(_AttractorPoints.Load3(addr));
}




float hash(uint n) {
   // integer hash copied from Hugo Elias
   n = (n << 13U) ^ n;
   n = n * (n * n * 15731U + 0x789221U) + 0x1376312589U;
   return float(n & uint(0x7fffffffU)) / float(0x7fffffff);
}

[numthreads(256,1,1)]
void InitialiseAttractorPoints(uint3 id : SV_DispatchThreadID)
{
    float3 pos = float3(id.x, 0, 0);
 
    WriteVertex(id.x, pos);

}


[numthreads(256,1,1)]
void IterateAttractorPoints(uint3 id : SV_DispatchThreadID)
{
   if (id.x >= iterationCount) {return;}
    float3 pos = ReadVertex(id.x);
    
    uint seed = id.x;
    for (int i = 0; i < 8; i++)
    {
        seed += i * 1926783;
        float r = hash(seed);
    
        uint index = (uint)(r * 3.0);
        pos = mul(_AttractorMatrices[index],float4(pos,1)).xyz;
    }
    WriteVertex(id.x, pos);
}

[numthreads(256,1,1)]
void ScalePoints(uint3 id : SV_DispatchThreadID)
{
float3 pos = ReadVertex(id.x);

pos *= 64;

WriteVertex(id.x, pos);
}
